spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  jpa:
    hibernate:
      ddl-auto: update
